const actions = {
  GET_DATA_JD: 'GET_DATA_JD',
  GET_DATA_JD_SUCCESS: 'GET_DATA_JD_SUCCESS',
  GET_DATA_CANDIDATE: 'GET_DATA_CANDIDATE',
  GET_DATA_CANDIDATE_SUCCESS: 'GET_DATA_CANDIDATE_SUCCESS',
  ADD_DATA_JD: 'ADD_DATA_JD',
  EDIT_DATA_JD: 'EDIT_DATA_JD',
  DELETE_DATA_JD: 'DELETE_DATA_JD',
  ADD_DATA_CANDIDATE: 'ADD_DATA_CANDIDATE',
  PAGINATION_DATA: 'PAGINATION_DATA',
  EDIT_DATA_CANDIDATE: 'EDIT_DATA_CANDIDATE',
  DELETE_DATA_CANDIDATE: 'DELETE_DATA_CANDIDATE',
  REDIRECT_LOGIN_TOKEN_EXP: 'REDIRECT_LOGIN_TOKEN_EXP',
};
export default actions;
